version: '3'
services:
  db:
    image: postgres:11.1
    container_name: postgres111
    volumes:
     - db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always             # run as a service
  odoo13:
    image: veivaa/odoo:13.0
    container_name: odoo13
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
  pgadmin:
    image: dpage/pgadmin4:4.25
    container_name: pgadmin4
    restart: always
    environment:
       PGADMIN_DEFAULT_EMAIL: admin
       PGADMIN_DEFAULT_PASSWORD: miclave
       PGADMIN_LISTEN_PORT: 80
    ports:
       - "8080:80"
    links:
       - "db:pgsql-server"
  nginx: 
    image: nginx:latest
    container_name: nginx
    depends_on:
      - odoo13
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  netdata:
    image: netdata/netdata
    container_name: netdata_status
    restart: always
    ports:
      - "19999:19999"
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
volumes:
  db-data:
    driver: local